/* Copyright (c) (2015,2019) Apple Inc. All rights reserved.
 *
 * corecrypto is licensed under Apple Inc.’s Internal Use License Agreement (which
 * is contained in the License.txt file distributed with corecrypto) and only to 
 * people who accept that license. IMPORTANT:  Any license rights granted to you by 
 * Apple Inc. (if any) are limited to internal use within your organization only on 
 * devices and computers you own or control, for the sole purpose of verifying the 
 * security characteristics and correct functioning of the Apple Software.  You may 
 * not, directly or indirectly, redistribute the Apple Software or any portions thereof.
*/

{"FFFFffffFFFFffffFFFFffffFFFFffff", "00000000000000010000000000000000"},
{"FFFFffffFFFFffffFFFFffffFFFFffff", "80000000000000000000000000000000"},
{"FFFFffffFFFFffffFFFFffffFFFFffff", "0FFFffffFFFFffffFFFFffffFFFFffff"},
{"FFFFffffFFFFffffFFFFffffFFFFffff", "FFFFffffFFFFffffFFFFffffFFFFffff"},
{"0000000000000011FFFFffffFFFFffff", "0000000000000001FFFFffffFFFFffff"},
{"0000000000000001FFFFffffFFFFffff", "0000000000000001FFFFffffFFFFffff"},
{"FFFFffffFFFFffffFFFFffffFFFFffff", "0000000000000001FFFFffffFFFFffff"},
{"9876543210abcdef9876543210abcdef9876543210abcdef", "8876543210abcdef9876543210abcdef9876543210abcdef"},
