/* Copyright (c) (2012,2015-2019,2021) Apple Inc. All rights reserved.
*
* corecrypto is licensed under Apple Inc.’s Internal Use License Agreement (which
* is contained in the License.txt file distributed with corecrypto) and only to
* people who accept that license. IMPORTANT:  Any license rights granted to you by
* Apple Inc. (if any) are limited to internal use within your organization only on
* devices and computers you own or control, for the sole purpose of verifying the
* security characteristics and correct functioning of the Apple Software.  You may
* not, directly or indirectly, redistribute the Apple Software or any portions thereof.
*/

/* Autogenerated file - Use scheme ccdh_gen_gp to regenerate */
#include "ccdh_internal.h"
#include <corecrypto/ccsrp_gp.h>

static ccdh_gp_decl_static(2048) _ccsrp_gp_rfc5054_2048 =
{
    .hp = {
        .n = ccn_nof(2048),
        .bitlen = 2048,
        .funcs = CCZP_FUNCS_DEFAULT
    },
    .p = {
        /* prime */
        CCN64_C(0f,a7,11,1f,9e,4a,ff,73),CCN64_C(9b,65,e3,72,fc,d6,8e,f2),
        CCN64_C(35,de,23,6d,52,5f,54,75),CCN64_C(94,b5,c8,03,d8,9f,7a,e4),
        CCN64_C(71,ae,35,f8,e9,db,fb,b6),CCN64_C(2a,56,98,f3,a8,d0,c3,82),
        CCN64_C(9c,cc,04,1c,7b,c3,08,d8),CCN64_C(af,87,4e,73,03,ce,53,29),
        CCN64_C(61,60,27,90,04,e5,7a,e6),CCN64_C(03,2c,fb,db,f5,2f,b3,78),
        CCN64_C(5e,a7,7a,27,75,d2,ec,fa),CCN64_C(54,45,23,b5,24,b0,d5,7d),
        CCN64_C(5b,9d,32,e6,88,f8,77,48),CCN64_C(f1,d2,b9,07,87,17,46,1a),
        CCN64_C(76,bd,20,7a,43,6c,64,81),CCN64_C(ca,97,b4,3a,23,fb,80,16),
        CCN64_C(1d,28,1e,44,6b,14,77,3b),CCN64_C(73,59,d0,41,d5,c3,3e,a7),
        CCN64_C(a8,0d,74,0a,db,f4,ff,74),CCN64_C(55,f9,79,93,ec,97,5e,ea),
        CCN64_C(29,18,a9,96,2f,0b,93,b8),CCN64_C(66,1a,05,fb,d5,fa,aa,e8),
        CCN64_C(cf,60,95,17,9a,16,3a,b3),CCN64_C(e8,08,39,69,ed,b7,67,b0),
        CCN64_C(cd,7f,48,a9,da,04,fd,50),CCN64_C(d5,23,12,ab,4b,03,31,0d),
        CCN64_C(81,93,e0,75,77,67,a1,3d),CCN64_C(a3,73,29,cb,b4,a0,99,ed),
        CCN64_C(fc,31,92,94,3d,b5,60,50),CCN64_C(af,72,b6,65,19,87,ee,07),
        CCN64_C(f1,66,de,5e,13,89,58,2f),CCN64_C(ac,6b,db,41,32,4a,9a,9b)
    },
    .p0inv = (cc_unit)4980855487231476293U,
    .r2 = {
        /* r2 */
        CCN64_C(c1,64,62,64,09,01,da,cc),CCN64_C(13,5b,6e,c8,da,57,79,26),
        CCN64_C(da,fd,a0,a8,dd,38,8c,e4),CCN64_C(26,6c,a5,e5,a2,ed,94,b6),
        CCN64_C(41,1d,08,a9,8f,8f,63,66),CCN64_C(d5,e9,43,5e,e9,d8,a0,e6),
        CCN64_C(cd,0a,37,f3,b1,55,d1,a9),CCN64_C(0a,09,59,9a,6d,ea,0b,27),
        CCN64_C(82,0c,95,96,54,8e,a6,c2),CCN64_C(65,a9,38,e0,b8,b0,6a,a4),
        CCN64_C(55,49,e0,80,ab,a4,ba,1a),CCN64_C(1a,fc,70,d2,f4,98,24,0e),
        CCN64_C(54,e5,3e,69,3a,1b,c8,42),CCN64_C(98,01,79,45,4e,b0,4b,8d),
        CCN64_C(5c,4d,14,b0,e0,0b,59,ef),CCN64_C(8b,5a,98,8c,fb,51,63,08),
        CCN64_C(c6,d6,6f,1c,08,b7,35,89),CCN64_C(26,c3,98,a8,4a,ca,56,eb),
        CCN64_C(01,2c,c3,70,2f,66,42,d2),CCN64_C(4b,53,0d,ed,23,75,f4,96),
        CCN64_C(e2,d9,b5,a7,bb,24,04,4a),CCN64_C(d0,c0,18,3e,10,7a,a7,4f),
        CCN64_C(7b,1c,1c,9b,72,72,da,4c),CCN64_C(3c,20,6b,89,30,c8,d7,08),
        CCN64_C(ae,42,85,3c,8d,f1,3b,4a),CCN64_C(e1,e2,b5,ed,0a,e8,7e,15),
        CCN64_C(54,ec,73,4b,c7,df,33,36),CCN64_C(66,09,4e,87,7b,6a,9b,f9),
        CCN64_C(25,84,d9,88,45,d6,ee,fd),CCN64_C(0a,0c,1f,1e,d6,37,89,3d),
        CCN64_C(1c,b0,8f,2d,d9,3b,be,46),CCN64_C(2a,59,f7,9b,0e,b8,3c,a8)
    },
    .g = {
        /* g */
        CCN64_C(00,00,00,00,00,00,00,02),CCN64_C(00,00,00,00,00,00,00,00),
        CCN64_C(00,00,00,00,00,00,00,00),CCN64_C(00,00,00,00,00,00,00,00),
        CCN64_C(00,00,00,00,00,00,00,00),CCN64_C(00,00,00,00,00,00,00,00),
        CCN64_C(00,00,00,00,00,00,00,00),CCN64_C(00,00,00,00,00,00,00,00),
        CCN64_C(00,00,00,00,00,00,00,00),CCN64_C(00,00,00,00,00,00,00,00),
        CCN64_C(00,00,00,00,00,00,00,00),CCN64_C(00,00,00,00,00,00,00,00),
        CCN64_C(00,00,00,00,00,00,00,00),CCN64_C(00,00,00,00,00,00,00,00),
        CCN64_C(00,00,00,00,00,00,00,00),CCN64_C(00,00,00,00,00,00,00,00),
        CCN64_C(00,00,00,00,00,00,00,00),CCN64_C(00,00,00,00,00,00,00,00),
        CCN64_C(00,00,00,00,00,00,00,00),CCN64_C(00,00,00,00,00,00,00,00),
        CCN64_C(00,00,00,00,00,00,00,00),CCN64_C(00,00,00,00,00,00,00,00),
        CCN64_C(00,00,00,00,00,00,00,00),CCN64_C(00,00,00,00,00,00,00,00),
        CCN64_C(00,00,00,00,00,00,00,00),CCN64_C(00,00,00,00,00,00,00,00),
        CCN64_C(00,00,00,00,00,00,00,00),CCN64_C(00,00,00,00,00,00,00,00),
        CCN64_C(00,00,00,00,00,00,00,00),CCN64_C(00,00,00,00,00,00,00,00),
        CCN64_C(00,00,00,00,00,00,00,00),CCN8_C(00)
    },
    .q = {
        /* q */
        CCN64_C(00,00,00,00,00,00,00,00),CCN64_C(00,00,00,00,00,00,00,00),
        CCN64_C(00,00,00,00,00,00,00,00),CCN64_C(00,00,00,00,00,00,00,00),
        CCN64_C(00,00,00,00,00,00,00,00),CCN64_C(00,00,00,00,00,00,00,00),
        CCN64_C(00,00,00,00,00,00,00,00),CCN64_C(00,00,00,00,00,00,00,00),
        CCN64_C(00,00,00,00,00,00,00,00),CCN64_C(00,00,00,00,00,00,00,00),
        CCN64_C(00,00,00,00,00,00,00,00),CCN64_C(00,00,00,00,00,00,00,00),
        CCN64_C(00,00,00,00,00,00,00,00),CCN64_C(00,00,00,00,00,00,00,00),
        CCN64_C(00,00,00,00,00,00,00,00),CCN64_C(00,00,00,00,00,00,00,00),
        CCN64_C(00,00,00,00,00,00,00,00),CCN64_C(00,00,00,00,00,00,00,00),
        CCN64_C(00,00,00,00,00,00,00,00),CCN64_C(00,00,00,00,00,00,00,00),
        CCN64_C(00,00,00,00,00,00,00,00),CCN64_C(00,00,00,00,00,00,00,00),
        CCN64_C(00,00,00,00,00,00,00,00),CCN64_C(00,00,00,00,00,00,00,00),
        CCN64_C(00,00,00,00,00,00,00,00),CCN64_C(00,00,00,00,00,00,00,00),
        CCN64_C(00,00,00,00,00,00,00,00),CCN64_C(00,00,00,00,00,00,00,00),
        CCN64_C(00,00,00,00,00,00,00,00),CCN64_C(00,00,00,00,00,00,00,00),
        CCN64_C(00,00,00,00,00,00,00,00),CCN8_C(00)
    },
    .l = 256,
};

ccdh_const_gp_t ccsrp_gp_rfc5054_2048(void)
{
    return (ccdh_const_gp_t)&_ccsrp_gp_rfc5054_2048;
}
