/* Copyright (c) (2012,2015-2019,2021) Apple Inc. All rights reserved.
*
* corecrypto is licensed under Apple Inc.’s Internal Use License Agreement (which
* is contained in the License.txt file distributed with corecrypto) and only to
* people who accept that license. IMPORTANT:  Any license rights granted to you by
* Apple Inc. (if any) are limited to internal use within your organization only on
* devices and computers you own or control, for the sole purpose of verifying the
* security characteristics and correct functioning of the Apple Software.  You may
* not, directly or indirectly, redistribute the Apple Software or any portions thereof.
*/

/* Autogenerated file - Use scheme ccdh_gen_gp to regenerate */
#include "ccdh_internal.h"
#include <corecrypto/ccsrp_gp.h>

static ccdh_gp_decl_static(1024) _ccsrp_gp_rfc5054_1024 =
{
    .hp = {
        .n = ccn_nof(1024),
        .bitlen = 1024,
        .funcs = CCZP_FUNCS_DEFAULT
    },
    .p = {
        /* prime */
        CCN64_C(9f,c6,1d,2f,c0,eb,06,e3),CCN64_C(fd,51,38,fe,83,76,43,5b),
        CCN64_C(2f,d4,cb,f4,97,6e,aa,9a),CCN64_C(68,ed,bc,3c,05,72,6c,c0),
        CCN64_C(c5,29,f5,66,66,0e,57,ec),CCN64_C(82,55,9b,29,7b,cf,18,85),
        CCN64_C(ce,8e,f4,ad,69,b1,5d,49),CCN64_C(5d,c7,d7,b4,61,54,d6,b6),
        CCN64_C(8e,49,5c,1d,60,89,da,d1),CCN64_C(e0,d5,d8,e2,50,b9,8b,e4),
        CCN64_C(38,3b,48,13,d6,92,c6,e0),CCN64_C(d6,74,df,74,96,ea,81,d3),
        CCN64_C(9e,a2,31,4c,9c,25,65,76),CCN64_C(60,72,61,87,75,ff,3c,0b),
        CCN64_C(9c,33,f8,0a,fa,8f,c5,e8),CCN64_C(ee,af,0a,b9,ad,b3,8d,d6)
    },
    .p0inv = (cc_unit)8865231070209741109U,
    .r2 = {
        /* r2 */
        CCN64_C(bb,00,ba,c6,bc,12,70,2a),CCN64_C(ac,14,91,e7,33,d4,c1,fe),
        CCN64_C(df,7a,9a,09,00,ba,95,bf),CCN64_C(01,f6,e7,50,eb,9a,4e,a3),
        CCN64_C(0f,53,f0,f7,cd,03,88,bf),CCN64_C(4a,a7,93,31,9a,30,92,a1),
        CCN64_C(01,6a,34,e5,85,6f,7f,c4),CCN64_C(f8,0a,26,f3,aa,ea,d6,35),
        CCN64_C(50,65,c3,ba,8f,66,92,34),CCN64_C(b3,33,07,1c,6f,37,20,5f),
        CCN64_C(2a,07,a5,22,00,e6,93,0d),CCN64_C(32,12,70,b0,e6,54,21,f7),
        CCN64_C(c8,31,39,a2,9e,46,16,ea),CCN64_C(f8,05,80,7d,17,38,d9,13),
        CCN64_C(55,60,06,7a,97,c7,90,a3),CCN64_C(1b,e3,b6,75,66,e0,4d,f8)
    },
    .g = {
        /* g */
        CCN64_C(00,00,00,00,00,00,00,02),CCN64_C(00,00,00,00,00,00,00,00),
        CCN64_C(00,00,00,00,00,00,00,00),CCN64_C(00,00,00,00,00,00,00,00),
        CCN64_C(00,00,00,00,00,00,00,00),CCN64_C(00,00,00,00,00,00,00,00),
        CCN64_C(00,00,00,00,00,00,00,00),CCN64_C(00,00,00,00,00,00,00,00),
        CCN64_C(00,00,00,00,00,00,00,00),CCN64_C(00,00,00,00,00,00,00,00),
        CCN64_C(00,00,00,00,00,00,00,00),CCN64_C(00,00,00,00,00,00,00,00),
        CCN64_C(00,00,00,00,00,00,00,00),CCN64_C(00,00,00,00,00,00,00,00),
        CCN64_C(00,00,00,00,00,00,00,00),CCN8_C(00)
    },
    .q = {
        /* q */
        CCN64_C(00,00,00,00,00,00,00,00),CCN64_C(00,00,00,00,00,00,00,00),
        CCN64_C(00,00,00,00,00,00,00,00),CCN64_C(00,00,00,00,00,00,00,00),
        CCN64_C(00,00,00,00,00,00,00,00),CCN64_C(00,00,00,00,00,00,00,00),
        CCN64_C(00,00,00,00,00,00,00,00),CCN64_C(00,00,00,00,00,00,00,00),
        CCN64_C(00,00,00,00,00,00,00,00),CCN64_C(00,00,00,00,00,00,00,00),
        CCN64_C(00,00,00,00,00,00,00,00),CCN64_C(00,00,00,00,00,00,00,00),
        CCN64_C(00,00,00,00,00,00,00,00),CCN64_C(00,00,00,00,00,00,00,00),
        CCN64_C(00,00,00,00,00,00,00,00),CCN8_C(00)
    },
    .l = 160,
};

ccdh_const_gp_t ccsrp_gp_rfc5054_1024(void)
{
    return (ccdh_const_gp_t)&_ccsrp_gp_rfc5054_1024;
}
