/* Copyright (c) (2011,2015-2019,2021) Apple Inc. All rights reserved.
*
* corecrypto is licensed under Apple Inc.’s Internal Use License Agreement (which
* is contained in the License.txt file distributed with corecrypto) and only to
* people who accept that license. IMPORTANT:  Any license rights granted to you by
* Apple Inc. (if any) are limited to internal use within your organization only on
* devices and computers you own or control, for the sole purpose of verifying the
* security characteristics and correct functioning of the Apple Software.  You may
* not, directly or indirectly, redistribute the Apple Software or any portions thereof.
*/

/* Autogenerated file - Use scheme ccdh_gen_gp to regenerate */
#include "ccdh_internal.h"
#include <corecrypto/ccdh_gp.h>

static ccdh_gp_decl_static(2048) _ccdh_gp_rfc3526group14 =
{
    .hp = {
        .n = ccn_nof(2048),
        .bitlen = 2048,
        .funcs = CCZP_FUNCS_DEFAULT
    },
    .p = {
        /* prime */
        CCN64_C(ff,ff,ff,ff,ff,ff,ff,ff),CCN64_C(15,72,8e,5a,8a,ac,aa,68),
        CCN64_C(15,d2,26,18,98,fa,05,10),CCN64_C(39,95,49,7c,ea,95,6a,e5),
        CCN64_C(de,2b,cb,f6,95,58,17,18),CCN64_C(b5,c5,5d,f0,6f,4c,52,c9),
        CCN64_C(9b,27,83,a2,ec,07,a2,8f),CCN64_C(e3,9e,77,2c,18,0e,86,03),
        CCN64_C(32,90,5e,46,2e,36,ce,3b),CCN64_C(f1,74,6c,08,ca,18,21,7c),
        CCN64_C(67,0c,35,4e,4a,bc,98,04),CCN64_C(9e,d5,29,07,70,96,96,6d),
        CCN64_C(1c,62,f3,56,20,85,52,bb),CCN64_C(83,65,5d,23,dc,a3,ad,96),
        CCN64_C(69,16,3f,a8,fd,24,cf,5f),CCN64_C(98,da,48,36,1c,55,d3,9a),
        CCN64_C(c2,00,7c,b8,a1,63,bf,05),CCN64_C(49,28,66,51,ec,e4,5b,3d),
        CCN64_C(ae,9f,24,11,7c,4b,1f,e6),CCN64_C(ee,38,6b,fb,5a,89,9f,a5),
        CCN64_C(0b,ff,5c,b6,f4,06,b7,ed),CCN64_C(f4,4c,42,e9,a6,37,ed,6b),
        CCN64_C(e4,85,b5,76,62,5e,7e,c6),CCN64_C(4f,e1,35,6d,6d,51,c2,45),
        CCN64_C(30,2b,0a,6d,f2,5f,14,37),CCN64_C(ef,95,19,b3,cd,3a,43,1b),
        CCN64_C(51,4a,08,79,8e,34,04,dd),CCN64_C(02,0b,be,a6,3b,13,9b,22),
        CCN64_C(29,02,4e,08,8a,67,cc,74),CCN64_C(c4,c6,62,8b,80,dc,1c,d1),
        CCN64_C(c9,0f,da,a2,21,68,c2,34),CCN64_C(ff,ff,ff,ff,ff,ff,ff,ff)
    },
    .p0inv = (cc_unit)1U,
    .r2 = {
        /* r2 */
        CCN64_C(47,71,22,ce,12,5f,b6,64),CCN64_C(b0,35,48,fb,9b,38,d3,13),
        CCN64_C(4c,21,53,ff,6f,d4,12,c1),CCN64_C(2a,09,2b,50,87,3f,9b,c6),
        CCN64_C(bb,c7,16,29,fc,b7,f5,f9),CCN64_C(4b,ec,06,e1,36,bd,84,e7),
        CCN64_C(27,ba,72,5a,6b,02,0c,b1),CCN64_C(f8,11,54,26,ed,93,9e,eb),
        CCN64_C(4b,c1,b1,87,8a,0e,30,d9),CCN64_C(56,20,82,0e,25,86,33,ff),
        CCN64_C(07,4e,d6,ab,78,5a,30,71),CCN64_C(f2,28,10,5f,81,f1,cb,61),
        CCN64_C(57,0e,43,6f,4e,2e,6f,7f),CCN64_C(5c,a5,2f,f7,d7,45,0b,d9),
        CCN64_C(55,22,72,d2,75,f1,0a,7e),CCN64_C(ac,2b,79,25,73,9c,79,78),
        CCN64_C(a2,f8,82,57,32,5b,54,d0),CCN64_C(bc,82,1c,9d,e8,d7,2b,d5),
        CCN64_C(db,d4,42,b3,86,6d,29,86),CCN64_C(94,78,95,1b,70,c4,b2,ce),
        CCN64_C(5d,99,8f,b3,94,91,0c,76),CCN64_C(f2,73,b2,93,7e,30,08,67),
        CCN64_C(8c,10,6b,be,38,56,9f,92),CCN64_C(f8,3c,92,cb,14,e9,92,c5),
        CCN64_C(d8,5d,6e,7e,ed,68,80,dd),CCN64_C(eb,5b,27,6f,be,06,a1,df),
        CCN64_C(2a,49,20,90,fa,11,e1,05),CCN64_C(63,bd,d9,6d,19,ea,00,be),
        CCN64_C(27,23,82,97,0a,16,98,ab),CCN64_C(8a,3a,68,6c,92,40,c9,74),
        CCN64_C(3e,d8,57,03,66,61,30,00),CCN64_C(0c,d3,7a,33,62,8b,31,97)
    },
    .g = {
        /* g */
        CCN64_C(00,00,00,00,00,00,00,02),CCN64_C(00,00,00,00,00,00,00,00),
        CCN64_C(00,00,00,00,00,00,00,00),CCN64_C(00,00,00,00,00,00,00,00),
        CCN64_C(00,00,00,00,00,00,00,00),CCN64_C(00,00,00,00,00,00,00,00),
        CCN64_C(00,00,00,00,00,00,00,00),CCN64_C(00,00,00,00,00,00,00,00),
        CCN64_C(00,00,00,00,00,00,00,00),CCN64_C(00,00,00,00,00,00,00,00),
        CCN64_C(00,00,00,00,00,00,00,00),CCN64_C(00,00,00,00,00,00,00,00),
        CCN64_C(00,00,00,00,00,00,00,00),CCN64_C(00,00,00,00,00,00,00,00),
        CCN64_C(00,00,00,00,00,00,00,00),CCN64_C(00,00,00,00,00,00,00,00),
        CCN64_C(00,00,00,00,00,00,00,00),CCN64_C(00,00,00,00,00,00,00,00),
        CCN64_C(00,00,00,00,00,00,00,00),CCN64_C(00,00,00,00,00,00,00,00),
        CCN64_C(00,00,00,00,00,00,00,00),CCN64_C(00,00,00,00,00,00,00,00),
        CCN64_C(00,00,00,00,00,00,00,00),CCN64_C(00,00,00,00,00,00,00,00),
        CCN64_C(00,00,00,00,00,00,00,00),CCN64_C(00,00,00,00,00,00,00,00),
        CCN64_C(00,00,00,00,00,00,00,00),CCN64_C(00,00,00,00,00,00,00,00),
        CCN64_C(00,00,00,00,00,00,00,00),CCN64_C(00,00,00,00,00,00,00,00),
        CCN64_C(00,00,00,00,00,00,00,00),CCN8_C(00)
    },
    .q = {
        /* q */
        CCN64_C(00,00,00,00,00,00,00,00),CCN64_C(00,00,00,00,00,00,00,00),
        CCN64_C(00,00,00,00,00,00,00,00),CCN64_C(00,00,00,00,00,00,00,00),
        CCN64_C(00,00,00,00,00,00,00,00),CCN64_C(00,00,00,00,00,00,00,00),
        CCN64_C(00,00,00,00,00,00,00,00),CCN64_C(00,00,00,00,00,00,00,00),
        CCN64_C(00,00,00,00,00,00,00,00),CCN64_C(00,00,00,00,00,00,00,00),
        CCN64_C(00,00,00,00,00,00,00,00),CCN64_C(00,00,00,00,00,00,00,00),
        CCN64_C(00,00,00,00,00,00,00,00),CCN64_C(00,00,00,00,00,00,00,00),
        CCN64_C(00,00,00,00,00,00,00,00),CCN64_C(00,00,00,00,00,00,00,00),
        CCN64_C(00,00,00,00,00,00,00,00),CCN64_C(00,00,00,00,00,00,00,00),
        CCN64_C(00,00,00,00,00,00,00,00),CCN64_C(00,00,00,00,00,00,00,00),
        CCN64_C(00,00,00,00,00,00,00,00),CCN64_C(00,00,00,00,00,00,00,00),
        CCN64_C(00,00,00,00,00,00,00,00),CCN64_C(00,00,00,00,00,00,00,00),
        CCN64_C(00,00,00,00,00,00,00,00),CCN64_C(00,00,00,00,00,00,00,00),
        CCN64_C(00,00,00,00,00,00,00,00),CCN64_C(00,00,00,00,00,00,00,00),
        CCN64_C(00,00,00,00,00,00,00,00),CCN64_C(00,00,00,00,00,00,00,00),
        CCN64_C(00,00,00,00,00,00,00,00),CCN8_C(00)
    },
    .l = 320,
};

ccdh_const_gp_t ccdh_gp_rfc3526group14(void)
{
    return (ccdh_const_gp_t)&_ccdh_gp_rfc3526group14;
}
