/* Copyright (c) (2011,2015-2019,2021) Apple Inc. All rights reserved.
*
* corecrypto is licensed under Apple Inc.’s Internal Use License Agreement (which
* is contained in the License.txt file distributed with corecrypto) and only to
* people who accept that license. IMPORTANT:  Any license rights granted to you by
* Apple Inc. (if any) are limited to internal use within your organization only on
* devices and computers you own or control, for the sole purpose of verifying the
* security characteristics and correct functioning of the Apple Software.  You may
* not, directly or indirectly, redistribute the Apple Software or any portions thereof.
*/

/* Autogenerated file - Use scheme ccdh_gen_gp to regenerate */
#include "ccdh_internal.h"
#include <corecrypto/ccdh_gp.h>

static ccdh_gp_decl_static(2048) _ccdh_gp_rfc5114_MODP_2048_256 =
{
    .hp = {
        .n = ccn_nof(2048),
        .bitlen = 2048,
        .funcs = CCZP_FUNCS_DEFAULT
    },
    .p = {
        /* prime */
        CCN64_C(db,09,4a,e9,1e,1a,15,97),CCN64_C(69,38,77,fa,d7,ef,09,ca),
        CCN64_C(61,16,d2,27,6e,11,71,5f),CCN64_C(a4,b5,43,30,c1,98,af,12),
        CCN64_C(75,f2,63,75,d7,01,41,03),CCN64_C(c3,a3,96,0a,54,e7,10,c3),
        CCN64_C(de,d4,01,0a,bd,0b,e6,21),CCN64_C(c0,b8,57,f6,89,96,28,56),
        CCN64_C(b3,ca,3f,79,71,50,60,26),CCN64_C(1c,ca,cb,83,e6,b4,86,f6),
        CCN64_C(67,e1,44,e5,14,05,64,25),CCN64_C(f6,a1,67,b5,a4,18,25,d9),
        CCN64_C(3a,d8,34,77,96,52,4d,8e),CCN64_C(f1,3c,6d,9a,51,bf,a4,ab),
        CCN64_C(2d,52,52,67,35,48,8a,0e),CCN64_C(b6,3a,ca,e1,ca,a6,b7,90),
        CCN64_C(4f,db,70,c5,81,b2,3f,76),CCN64_C(bc,39,a0,bf,12,30,7f,5c),
        CCN64_C(b9,41,f5,4e,b1,e5,9b,b8),CCN64_C(6c,5b,fc,11,d4,5f,90,88),
        CCN64_C(22,e0,b1,ef,42,75,bf,7b),CCN64_C(91,f9,e6,72,5b,47,58,c0),
        CCN64_C(5a,8a,9d,30,6b,cf,67,ed),CCN64_C(20,9e,0c,64,97,51,7a,bd),
        CCN64_C(3b,f4,29,6d,83,0e,9a,7c),CCN64_C(16,c3,d9,11,34,09,6f,aa),
        CCN64_C(fa,f7,df,45,61,b2,aa,30),CCN64_C(e0,0d,f8,f1,d6,19,57,d4),
        CCN64_C(5d,2c,ee,d4,43,5e,3b,00),CCN64_C(8c,ee,f6,08,66,0d,d0,f2),
        CCN64_C(ff,bb,d1,9c,65,19,59,99),CCN64_C(87,a8,e6,1d,b4,b6,66,3c)
    },
    .p0inv = (cc_unit)5902669834146956761U,
    .r2 = {
        /* r2 */
        CCN64_C(7c,40,f7,8c,b5,15,9c,e0),CCN64_C(1f,af,47,7b,ab,1a,21,b6),
        CCN64_C(32,82,8c,0b,87,4d,c9,38),CCN64_C(43,d6,72,36,4d,04,f6,ce),
        CCN64_C(e8,a5,08,71,0a,b3,f3,ac),CCN64_C(cc,65,eb,92,d9,a0,02,9f),
        CCN64_C(4c,3f,3c,58,5e,2f,67,37),CCN64_C(06,51,2d,26,0a,4d,b4,49),
        CCN64_C(ec,a6,eb,1d,e9,9f,38,50),CCN64_C(27,b3,b3,77,a7,bb,19,b3),
        CCN64_C(b5,4a,04,50,81,5c,f3,eb),CCN64_C(e3,f0,50,fa,95,df,bd,2d),
        CCN64_C(1b,b7,9e,16,8c,b0,f9,dc),CCN64_C(42,00,f3,b9,26,8f,38,df),
        CCN64_C(98,34,05,5e,04,86,d5,07),CCN64_C(83,8c,f3,9f,4c,3f,f9,84),
        CCN64_C(40,4b,b2,2f,be,52,39,f8),CCN64_C(23,1d,37,bd,5b,76,55,60),
        CCN64_C(e4,cf,e8,98,bb,a2,09,79),CCN64_C(dc,d9,7e,8c,c8,e6,e7,42),
        CCN64_C(8b,0c,17,96,c8,bb,71,22),CCN64_C(fb,e9,b5,40,b7,87,97,c6),
        CCN64_C(c9,fa,aa,24,26,1b,0c,a4),CCN64_C(6e,8d,1c,2d,6b,b4,cb,11),
        CCN64_C(95,40,05,08,af,85,f3,35),CCN64_C(a9,3a,cc,88,0b,43,ab,cd),
        CCN64_C(4d,36,74,36,84,4e,85,e2),CCN64_C(d4,fb,52,77,3f,60,05,79),
        CCN64_C(85,fa,24,89,1e,e2,f6,47),CCN64_C(cd,5a,8c,bd,be,90,6b,63),
        CCN64_C(bb,a6,e0,4b,85,97,f8,3a),CCN64_C(61,d7,22,d4,46,0e,d3,57)
    },
    .g = {
        /* g */
        CCN64_C(66,4b,4c,0f,6c,c4,16,59),CCN64_C(5e,23,27,cf,ef,98,c5,82),
        CCN64_C(d6,47,d1,48,d4,79,54,51),CCN64_C(2f,63,07,84,90,f0,0e,f8),
        CCN64_C(18,4b,52,3d,1d,b2,46,c3),CCN64_C(c7,89,14,28,cd,c6,7e,b6),
        CCN64_C(7f,d0,28,37,0d,f9,2b,52),CCN64_C(b3,35,3b,bb,64,e0,ec,37),
        CCN64_C(ec,d0,6e,15,57,cd,09,15),CCN64_C(b7,d2,bb,d2,df,01,61,99),
        CCN64_C(c8,48,4b,1e,05,25,88,b9),CCN64_C(db,2a,3b,73,13,d3,fe,14),
        CCN64_C(d0,52,b9,85,d1,82,ea,0a),CCN64_C(a4,bd,1b,ff,e8,3b,9c,80),
        CCN64_C(df,c9,67,c1,fb,3f,2e,55),CCN64_C(b5,04,5a,f2,76,71,64,e1),
        CCN64_C(1d,14,34,8f,6f,2f,91,93),CCN64_C(64,e6,79,82,42,8e,bc,83),
        CCN64_C(8a,c3,76,d2,82,d6,ed,38),CCN64_C(77,7d,e6,2a,aa,b8,a8,62),
        CCN64_C(dd,f4,63,e5,e9,ec,14,4b),CCN64_C(01,96,f9,31,c7,7a,57,f2),
        CCN64_C(a5,5a,e3,13,41,00,0a,65),CCN64_C(90,12,28,f8,c2,8c,bb,18),
        CCN64_C(bc,37,73,bf,7e,8c,6f,62),CCN64_C(be,3a,6c,1b,0c,6b,47,b1),
        CCN64_C(ff,4f,ed,4a,ac,0b,b5,55),CCN64_C(10,db,c1,50,77,be,46,3f),
        CCN64_C(07,f4,79,3a,1a,0b,a1,25),CCN64_C(4c,a7,b1,8f,21,ef,20,54),
        CCN64_C(2e,77,50,66,60,ed,bd,48),CCN64_C(3f,b3,2c,9b,73,13,4d,0b)
    },
    .q = {
        /* q */
        CCN64_C(a3,08,b0,fe,64,f5,fb,d3),CCN64_C(99,b1,a4,7d,1e,b3,75,0b),
        CCN64_C(b4,47,99,76,40,12,9d,a2),CCN64_C(8c,f8,36,42,a7,09,a0,97),
        CCN64_C(00,00,00,00,00,00,00,00),CCN64_C(00,00,00,00,00,00,00,00),
        CCN64_C(00,00,00,00,00,00,00,00),CCN64_C(00,00,00,00,00,00,00,00),
        CCN64_C(00,00,00,00,00,00,00,00),CCN64_C(00,00,00,00,00,00,00,00),
        CCN64_C(00,00,00,00,00,00,00,00),CCN64_C(00,00,00,00,00,00,00,00),
        CCN64_C(00,00,00,00,00,00,00,00),CCN64_C(00,00,00,00,00,00,00,00),
        CCN64_C(00,00,00,00,00,00,00,00),CCN64_C(00,00,00,00,00,00,00,00),
        CCN64_C(00,00,00,00,00,00,00,00),CCN64_C(00,00,00,00,00,00,00,00),
        CCN64_C(00,00,00,00,00,00,00,00),CCN64_C(00,00,00,00,00,00,00,00),
        CCN64_C(00,00,00,00,00,00,00,00),CCN64_C(00,00,00,00,00,00,00,00),
        CCN64_C(00,00,00,00,00,00,00,00),CCN64_C(00,00,00,00,00,00,00,00),
        CCN64_C(00,00,00,00,00,00,00,00),CCN64_C(00,00,00,00,00,00,00,00),
        CCN64_C(00,00,00,00,00,00,00,00),CCN64_C(00,00,00,00,00,00,00,00),
        CCN64_C(00,00,00,00,00,00,00,00),CCN64_C(00,00,00,00,00,00,00,00),
        CCN64_C(00,00,00,00,00,00,00,00),CCN8_C(00)
    },
    .l = 0,
};

ccdh_const_gp_t ccdh_gp_rfc5114_MODP_2048_256(void)
{
    return (ccdh_const_gp_t)&_ccdh_gp_rfc5114_MODP_2048_256;
}
