/* Copyright (c) (2019,2020) Apple Inc. All rights reserved.
 *
 * corecrypto is licensed under Apple Inc.’s Internal Use License Agreement (which
 * is contained in the License.txt file distributed with corecrypto) and only to
 * people who accept that license. IMPORTANT:  Any license rights granted to you by
 * Apple Inc. (if any) are limited to internal use within your organization only on
 * devices and computers you own or control, for the sole purpose of verifying the
 * security characteristics and correct functioning of the Apple Software.  You may
 * not, directly or indirectly, redistribute the Apple Software or any portions thereof.
 */

    { .keyStr=keystr192,.block_ivStr=ivstr64, .ptStr=zeroX16, "a38feed967ba6cfe6f2417e54f7b5260", NULL },
    { .keyStr=keystr192,.block_ivStr=ivstr64, .ptStr=zeroX32, "a38feed967ba6cfe6f2417e54f7b5260ed6430b817a27ce3746407017aa59d77", NULL },
    { .keyStr=keystr192,.block_ivStr=ivstr64, .ptStr=zeroX64, "a38feed967ba6cfe6f2417e54f7b5260ed6430b817a27ce3746407017aa59d776abe8fff018b09bec17d5938c4f23100", NULL },

