/* Copyright (c) (2011,2015,2016,2018,2019) Apple Inc. All rights reserved.
 *
 * corecrypto is licensed under Apple Inc.’s Internal Use License Agreement (which
 * is contained in the License.txt file distributed with corecrypto) and only to 
 * people who accept that license. IMPORTANT:  Any license rights granted to you by 
 * Apple Inc. (if any) are limited to internal use within your organization only on 
 * devices and computers you own or control, for the sole purpose of verifying the 
 * security characteristics and correct functioning of the Apple Software.  You may 
 * not, directly or indirectly, redistribute the Apple Software or any portions thereof.
 */

/* Autogenerated file - Use scheme ccdh_gen_gp to regenerate */
#ifndef _CORECRYPTO_CCDH_GP_H_
#define _CORECRYPTO_CCDH_GP_H_

#include <corecrypto/ccdh.h>

ccdh_const_gp_t ccdh_gp_apple768(void);
ccdh_const_gp_t ccdh_gp_rfc5114_MODP_1024_160(void);
ccdh_const_gp_t ccdh_gp_rfc5114_MODP_2048_224(void);
ccdh_const_gp_t ccdh_gp_rfc5114_MODP_2048_256(void);
ccdh_const_gp_t ccdh_gp_rfc2409group02(void);
ccdh_const_gp_t ccdh_gp_rfc3526group05(void);
ccdh_const_gp_t ccdh_gp_rfc3526group14(void);
ccdh_const_gp_t ccdh_gp_rfc3526group15(void);
ccdh_const_gp_t ccdh_gp_rfc3526group16(void);
ccdh_const_gp_t ccdh_gp_rfc3526group17(void);
ccdh_const_gp_t ccdh_gp_rfc3526group18(void);
ccdh_const_gp_t ccsrp_gp_rfc5054_1024(void);
ccdh_const_gp_t ccsrp_gp_rfc5054_2048(void);
ccdh_const_gp_t ccsrp_gp_rfc5054_3072(void);
ccdh_const_gp_t ccsrp_gp_rfc5054_4096(void);
ccdh_const_gp_t ccsrp_gp_rfc5054_8192(void);

#endif /* _CORECRYPTO_CCDH_GP_H_ */
