#!/usr/bin/perl
#
# Copyright (c) 2004 Apple Computer, Inc. All rights reserved.
#
# @APPLE_LICENSE_HEADER_START@
# 
# This file contains Original Code and/or Modifications of Original Code
# as defined in and that are subject to the Apple Public Source License
# Version 2.0 (the 'License'). You may not use this file except in
# compliance with the License. Please obtain a copy of the License at
# http://www.opensource.apple.com/apsl/ and read it before using this
# file.
# 
# The Original Code and all software distributed under the License are
# distributed on an 'AS IS' basis, WITHOUT WARRANTY OF ANY KIND, EITHER
# EXPRESS OR IMPLIED, AND APPLE HEREBY DISCLAIMS ALL SUCH WARRANTIES,
# INCLUDING WITHOUT LIMITATION, ANY WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE, QUIET ENJOYMENT OR NON-INFRINGEMENT.
# Please see the License for the specific language governing rights and
# limitations under the License.
# 
# @APPLE_LICENSE_HEADER_END@

use strict;

# combine arguments without a slash, with the preceding argument with a slash
# use @ instead of space for separator
my @args;
my $prev;
for(@ARGV) {
    if(m,/,) {
	push(@args, $prev) if $prev;
	$prev = $_;
    } else {
	$prev .= "\@$_";
    }
}
push(@args, $prev) if $prev;

# now make all unique combinations
my %combos;
foreach my $variant (sort(@args)) {
    my($v, $defines) = split('/', $variant, 2);
    my %new;
    @new{$v, map("$_-$v", sort(keys %combos))} = ($defines, map("$_\@$defines", sort(values %combos)));
    %combos = (%combos, %new);
}
for(sort keys(%combos)) {
    printf "%s/%s\n", $_, $combos{$_};
}
