.PATH: ${.CURDIR}/${MACHINE_ARCH}/internat ${.CURDIR}/internat

MISRCS += NXCType.c     NXIsCntrl.c   NXIsPrint.c   NXIsXDigit.c  _NXToLower.c \
        NXIsAlNum.c   NXIsDigit.c   NXIsPunct.c   NXToAscii.c   _NXToUpper.c \
        NXIsAlpha.c   NXIsGraph.c   NXIsSpace.c   NXToLower.c \
        NXIsAscii.c   NXIsLower.c   NXIsUpper.c   NXToUpper.c 
